### ISSUE TITLE
MacOS font error w/ AncestralSequenceReconstruction_TreeTime

### ISSUE THREAD

**Issue by mckennalewis11** [niemasd/ViReport#14]
I  repulled and ran ViReport again but when I have been having this issue at this step of the pipeline( w/ old and new ViReport version) : 

Running 'AncestralSequenceReconstruction_TreeTime'...
qt.qpa.fonts: Populating font family aliases took 1019 ms. Replace uses of missing font family "Noto Sans" with one that exists to avoid this cost. objc[41417]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff9f1f23d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x12ae72f50). One of the two will be used. Which one is undefined.

Which from my research(googling) looks specific to Mac OS. Tried a few things to troubleshoot it, none were that successful, do you have any recommendations? 

I attached my files from running it and my data( in firstDir) and the zika files
[firstDir.zip](https://github.com/niemasd/ViReport/files/4483326/firstDir.zip)
[zika_dates.tsv.zip](https://github.com/niemasd/ViReport/files/4483335/zika_dates.tsv.zip)
[zika.fas.zip](https://github.com/niemasd/ViReport/files/4483336/zika.fas.zip)

Thanks!
McKenna

**Comment by niemasd** [comment]
Very strange! I don't think ancestral state reconstruction is super interesting anyways, so go ahead and run ViReport using ``--ancestral None`` to just skip that step entirely (should be in the most recent pull)
