### ISSUE TITLE
WriteReport Issue

### ISSUE THREAD

**Issue by mckennalewis11** [niemasd/ViReport#15]
Hey Niema!

So I am getting this issue in the last step of the pipeline, and I know collin had this issue earlier as well. Is there anything I should be doing differently? ( I reran it with the latest pull and collin is in the process of rerunning it with the latest pull as well). thanks!

[2020-04-15 16:13:41] Writing report using 'WriteReport_Default'...
Traceback (most recent call last):
  File "./ViReport.py", line 144, in <module>
    GC.SELECTED['Driver'].run(GC.OUT_DIR_INFILES_SEQS, GC.REF_ID, GC.OUT_DIR_INFILES_TIMES, GC.OUT_DIR_INFILES_OUTGROUPS, GC.OUT_DIR_INFILES_CATEGORIES)
  File "/Users/mckennalewis/Desktop/ViReport/modules/Driver_Default.py", line 143, in run
    GC.REPORT = GC.SELECTED['WriteReport'].write_report()
  File "/Users/mckennalewis/Desktop/ViReport/modules/WriteReport_Default.py", line 39, in write_report
    for l in GC.read_file(GC.INPUT_OUTGROUPS):
  File "/Users/mckennalewis/Desktop/ViReport/modules/ViReport_GlobalContext.py", line 60, in read_file
    if fn.lower().endswith('.gz'):
AttributeError: 'NoneType' object has no attribute 'lower'

I attached the files and my zika data :) 
[zika_dates.tsv.zip](https://github.com/niemasd/ViReport/files/4484257/zika_dates.tsv.zip)
[zika.fas.zip](https://github.com/niemasd/ViReport/files/4484258/zika.fas.zip)
[firstDir.zip](https://github.com/niemasd/ViReport/files/4484259/firstDir.zip)

**Comment by niemasd** [comment]
Woops, good catch! Fixing now, I'll let you know when I push

**Comment by niemasd** [comment]
Okay, fixed! However, in your output folder, it seems like treedater crashed (but didn't crash ViReport; something I need to fix)

**Comment by mckennalewis11** [comment]
okay awesome thanks :) before I repulled it look like 3 hours, and then the second time I ran it, it only took like 1 so that makes sense
