### ISSUE TITLE
Treedater can't optimize rate parameters

### ISSUE THREAD

**Issue by Cyoung02** [niemasd/ViReport#16]
When running ViReport, treedater produced another nondescript error. Upon further investigation, the treedater warnings.txt file had this error:
![image](https://user-images.githubusercontent.com/46090395/79416549-c7935480-7f64-11ea-90d8-18573c110b12.png)
For convenience, here's the run_treedater.R:
![image](https://user-images.githubusercontent.com/46090395/79416621-eb569a80-7f64-11ea-8e29-0f5d53e21f7e.png)

The rest of the output files for this particular run are [here](https://github.com/Cyoung02/ViReport-Ebola/tree/master/PhyloTools/IQTree)

**Comment by niemasd** [comment]
Interesting, that's a great catch. I basically try to speed up treedater by trying to roughly estimate the mutation rate (``omega0``), but it seems like the rough estimate was bogus here. I'll add an if-statement to check if the estimated rate seems valid, and if it doesn't, just let treedater do its thing from scratch. I'll let you know when I push

**Comment by niemasd** [comment]
Should be fixed now!

**Comment by Cyoung02** [comment]
Hmm. I've given it another run and the pipeline got farther, but I got this error, which resulted in a file not found when writing the report. 
![image](https://user-images.githubusercontent.com/46090395/79644735-b2364a00-815f-11ea-8002-ac3db7bfa0c6.png)
In the treedater/warnings.txt file it seems like the same error popped up. Maybe my data is the issue?
![image](https://user-images.githubusercontent.com/46090395/79644801-13f6b400-8160-11ea-98ca-efccf7d097d6.png)
![image](https://user-images.githubusercontent.com/46090395/79644845-5d470380-8160-11ea-8c1b-7c9a8b0d7bf6.png)

[Here](https://github.com/Cyoung02/ViReport-Ebola/tree/master/PhyloTools/IQTreeMFP) are the files for this run.

**Comment by niemasd** [comment]
Very weird, 0.000000 should have been smaller than my threshold. I tried making my zero threshold larger; can you try pulling and trying again?

**Comment by Cyoung02** [comment]
it worked this time around! thanks
