### ISSUE TITLE
issues at the tree step in ViReport pipeline

### ISSUE THREAD

**Issue by mckennalewis11** [niemasd/ViReport#17]
Hey Niema! 

So ViReport generated part of the report (woohooo !!), but then had this error. Any recommendations on what I should do, Attached all files, figures are in firstDir/reportfiles

[firstDir.zip](https://github.com/niemasd/ViReport/files/4497561/firstDir.zip)
[zika_dates.tsv.zip](https://github.com/niemasd/ViReport/files/4497564/zika_dates.tsv.zip)
[zika.fas.zip](https://github.com/niemasd/ViReport/files/4497565/zika.fas.zip)

**Comment by mckennalewis11** [comment]
here is screenshot of error(Sorry forgot to attach) 
<img width="1314" alt="Screen Shot 2020-04-18 at 1 19 32 PM" src="https://user-images.githubusercontent.com/41457890/79670428-c6864100-8177-11ea-9649-13cea7ad4af6.png">

**Comment by niemasd** [comment]
Yay, that's great! I think I may have encountered that before, and I *think* I had fixed it. Can you try pulling the most recent ViReport and trying again? You can just delete the report stuff and run it with ``--continue_workflow`` to avoid recomputing anything (as you seem to already be doing)

**Comment by mckennalewis11** [comment]
yep! will do right now

**Comment by mckennalewis11** [comment]
<img width="1129" alt="Screen Shot 2020-04-18 at 3 04 33 PM" src="https://user-images.githubusercontent.com/41457890/79672359-f2102800-8185-11ea-9d2c-232f2992d13c.png">
it went for longer this time, but new error here, and I see that it looks like the year is formatted wrong, but I am not sure how I would fix this? (besides removing that data point, also sorry to ask so many questions )

**Comment by niemasd** [comment]
Yeah it looks like the date is messed up. Maybe take a look at the dates and see what's up with them? If it's just one faulty date, you can just remove it, but if they're all messed up, we might need to dig deeper into where the data came from. And no worries, questions are good!

**Comment by niemasd** [comment]
I think I figured out why you got the "cannot parse as Newick" error as well: it seems like ``treedater`` takes up a bunch of memory, so it may have crashed and not produced a dated tree. I have to update ViReport to crash when any of the modules' tools crashes

**Comment by mckennalewis11** [comment]
okay! I can repull. I still haven't been able to find where that faulty date was, Collin had looked at the data too, but maybe we were both looking in the wrong place.  I attached the directory w/ all the files. 
[firstDir.zip](https://github.com/niemasd/ViReport/files/4500357/firstDir.zip)
( update: collin ran it with my input files and got the same error w/ the dates )
