### ISSUE TITLE
Stuck at writing report?

### ISSUE THREAD

**Issue by Cyoung02** [niemasd/ViReport#18]
ViReport has been on the last step for about two hours now, and I thought this was strange given that all the actual analyses themselves had finished. 
![image](https://user-images.githubusercontent.com/46090395/79676888-a36f8780-819f-11ea-836a-6d897d25ee2c.png)
When I checked the output folder, it would seem like the reports are generated, so I'm not sure why ViReport hasn't terminated yet.

[Here](https://github.com/Cyoung02/ViReport-Ebola/tree/master/PhyloTools/IQTreeMFP) are the files.

**Comment by Cyoung02** [comment]
It seems like it was an issue with the latex pdf generation. When I ran the command manually, I had to press enter after each question mark for it to finish running. [Here's](https://github.com/Cyoung02/ViReport-Ebola/blob/master/PhyloTools/IQTreeMFP/report_files/main.log) the latex log.

**Comment by niemasd** [comment]
Yeah I've been having issues with outputting as LaTeX. I might swap it out to a different thing to generate PDFs. For now, it may be better to do ``--format Markdown``

**Comment by Cyoung02** [comment]
Sounds good!
