### ISSUE TITLE
LSD2 requires additional -s argument 

### ISSUE THREAD

**Issue by Cyoung02** [niemasd/ViReport#19]
Dating the tree with LSD2 seems to also want us to provide a sequence length argument.
![image](https://user-images.githubusercontent.com/46090395/79694658-9fd31380-8226-11ea-9810-ee5ede05c748.png)
The lsd2 command was called as follows:
```
lsd2 -c -i /home/colin/Desktop/NiemaLab/testingViReport/Analysis/DatingTools/LSD2/intermediate_files/LSD2/tree_unzipped.tre -d /home/colin/Desktop/NiemaLab/testingViReport/Analysis/DatingTools/LSD2/intermediate_files/LSD2/times_lsd.txt
```  
[Here](https://github.com/Cyoung02/ViReport-Ebola/tree/master/DatingTools/LSD2) are the rest of the files for this run.

**Comment by niemasd** [comment]
Strange, I don't know why it runs locally without it for me! Regardless, it seems like they by default use a length of 1000 even if you specify a length > 1000, so I've hard-coded it in. I'll fix it in the future to actually pull the alignment length if it makes a difference in the future

Try pulling again, and it should be fixed!

**Comment by Cyoung02** [comment]
Yes that worked! Thanks.
