### ISSUE TITLE
MAFFT Crash

### ISSUE THREAD

**Issue by Cyoung02** [niemasd/ViReport#6]
Running the program as follows gave an error:
./ViReport.py -s ../Ebola_Sequences.fasta -t ../Sample_Times.tsv -o ~/Desktop/NiemaLab/testingViReport/Results

![image](https://user-images.githubusercontent.com/46090395/78511497-f4b85980-7751-11ea-97c1-5fecf5a099e3.png)

Here are the files I ran ViReport with: 
[error.zip](https://github.com/niemasd/ViReport/files/4435077/error.zip)

**Comment by Cyoung02** [comment]
Running the program as follows gave an error:
./ViReport.py -s ../Ebola_Sequences.fasta -t ../Sample_Times.tsv -o ~/Desktop/NiemaLab/testingViReport/Results

![image](https://user-images.githubusercontent.com/46090395/78511497-f4b85980-7751-11ea-97c1-5fecf5a099e3.png)

Here are the files I ran ViReport with: 
[error.zip](https://github.com/niemasd/ViReport/files/4435077/error.zip)

**Comment by niemasd** [comment]
Are you sure ``mafft`` is in your ``PATH``? It seems to be working fine for me. In your output folder, there should be a file ``output_folder/intermediate_files/MAFFT/log.txt``. Can you attach that?

**Comment by Cyoung02** [comment]
It should be in the zip file I've attached: the output_folder is named Results

**Comment by niemasd** [comment]
It seems like MAFFT was running properly, but then it crashed. Can you try running it again and keep an eye on your computer's RAM usage? I'm guessing it might be crashing from memory consumption perhaps?

**Comment by Cyoung02** [comment]
Sure, I've attached the log file below. It should also be in the zip file I attached to the original post (the output file is Results). I've double checked the MAFFT install location and it should be in my ``PATH``. 
[log.txt](https://github.com/niemasd/ViReport/files/4435544/log.txt)

**Comment by Cyoung02** [comment]
You're right. The process suddenly spikes in memory usage and then it crashes.

**Comment by niemasd** [comment]
Is there a reference genome we can use? Perhaps something here?

https://www.ncbi.nlm.nih.gov/genomes/GenomesGroup.cgi?taxid=186536

If so, we can use the Minimap2 MSA module of ViReport, which would be faster and lower memory

**Comment by Cyoung02** [comment]
I just freed up some memory on my computer and it worked. Thanks!
