### ISSUE TITLE
No such file error when running treedater

### ISSUE THREAD

**Issue by Cyoung02** [niemasd/ViReport#8]
I ran ViReport as follows: 
<pre><code>./ViReport.py -s ../Ebola_Sequences.fasta -t ../Sample_Times.tsv -o ~/Desktop/NiemaLab/testingViReport/Results --continue_workflow </code></pre>

Continuing the workflow after rooting the phylogeny returned this error while treedater was running. 
![image](https://user-images.githubusercontent.com/46090395/78970029-38e28b80-7abd-11ea-96ae-2c540c411bc7.png)

Here's the output folder:
[Results.zip](https://github.com/niemasd/ViReport/files/4460325/Results.zip)

**Comment by niemasd** [comment]
The folder in the zip seems to be empty. Can you try attaching just ``Ebola_Sequences.fasta`` and ``Sample_Times.tsv``? I'll run it, then delete everything after rooting, and then run it again

**Comment by Cyoung02** [comment]
Hmm that's weird. Here are the input files.
[input_files.zip](https://github.com/niemasd/ViReport/files/4462476/input_files.zip)

**Comment by niemasd** [comment]
This zip file is also empty. Is it possible to directly attach the plain-text files (like the actual FASTA file, then the actual TSV file)?

**Comment by Cyoung02** [comment]
The sizes are too big so I have to compress them first. I double checked this one and it (hopefully) should not be empty.
[input_files.zip](https://github.com/niemasd/ViReport/files/4462485/input_files.zip)

**Comment by niemasd** [comment]
Yup, that one worked! Thanks! It's running right now; I'll update you once it's done

**Comment by niemasd** [comment]
Can you also attach multiple sequence alignment so I can skip that step?

**Comment by Cyoung02** [comment]
Sure. Here's the MSA
[sequences_safe.aln.gz](https://github.com/niemasd/ViReport/files/4462901/sequences_safe.aln.gz)

**Comment by Cyoung02** [comment]
I've also created a repo of the Ebola analysis [here](https://github.com/Cyoung02/ViReport-Ebola), if that makes things easier at all.

**Comment by niemasd** [comment]
Found the issue: the alignment file in the output directory isn't correct. It has the following contents:

```
version https://git-lfs.github.com/spec/v1
oid sha256:fbb2f30868d507b160351131ce0a758ab465a0d554576a638a4e97594a188ee5
size 31566105
```

I think you may have accidentally corrupted something along the way. Regardless, I should add a safety check to give a more helpful error message if it encounters an invalid FASTA

**Comment by Cyoung02** [comment]
Ah I see, thanks! I'll rerun the analysis from the beginning

**Comment by Cyoung02** [comment]
Running the pipeline again resulted in the same thing- I think the alignment file you found was a pointer. I used Git Large File Storage (LFS) which replaces large files with text pointers inside Git, while storing the file contents on a remote server, since the file was too large to be uploaded directly to github.

**Comment by niemasd** [comment]
Try running ViReport with ``-gz`` to gzip the output files

**Comment by Cyoung02** [comment]
I've run it with -gz and updated all the files in the Ebola repo to be compressed.

**Comment by niemasd** [comment]
Nice!

**Comment by Cyoung02** [comment]
Figured it out! I had to manually create an empty dated.tre file in the intermediate_files/treedater directory first, then treedater worked in the pipeline.

**Comment by Cyoung02** [comment]
Turns out some of my sequences didn't have sample times associated with it. I'm going to remove them and give it another shot.
